version: "3.3"
services:
  build_env:
    build: "docker/."
    container_name: "d2dcn_gui_dwc"
    image: "d2dcn_gui_dwi"
    volumes:
      - .:/home/docker/workspace
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    environment:
      - DISPLAY=:0
    stdin_open: true 
    tty: true
    privileged: true
